const db=require('./store/db');
const {decrypt}=require('./security');
function csv(v){return String(v||'').split(/[\n,]/).map(x=>x.trim()).filter(Boolean)}
function bool(v,f=false){if(v===undefined||v===null||v==='')return f;return['1','true','yes','on'].includes(String(v).trim().toLowerCase())}
function secret(v){try{return decrypt(v||'')}catch{return''}}
function runtimeSettings(){const s=db.read().settings||{},r=s.runtime||{},search=r.search||{},x=r.x||{},ai=r.ai||{},automation=r.automation||{};return{timezone:s.timezone||process.env.ORVIA_TIMEZONE||'Africa/Lagos',niche:r.niche||process.env.NICHE||'technology and creator economy',queries:Array.isArray(r.queries)&&r.queries.length?r.queries:csv(process.env.SCOUT_QUERIES||'creator economy trends,AI creator tools,social media monetization trends'),maxOpportunities:Math.max(1,Math.min(20,Number(r.maxOpportunities||process.env.MAX_OPPORTUNITIES||5))),searchProvider:String(search.provider||process.env.SEARCH_PROVIDER||'tavily').toLowerCase(),tavilyApiKey:secret(search.tavilyApiKey)||process.env.TAVILY_API_KEY||'',xAccounts:Array.isArray(x.accounts)?x.accounts:csv(process.env.X_ACCOUNTS||''),xBearerToken:secret(x.bearerToken)||process.env.X_BEARER_TOKEN||'',aiBaseUrl:ai.baseUrl||process.env.AI_BASE_URL||'https://api.openai.com/v1',aiApiKey:secret(ai.apiKey)||process.env.AI_API_KEY||process.env.OPENAI_API_KEY||'',aiModel:ai.model||process.env.AI_MODEL||'gpt-5.6-luna',automation:{enabled:automation.enabled??bool(process.env.AUTO_MODE,true),cycleMinutes:Math.max(5,Math.min(1440,Number(automation.cycleMinutes||process.env.AUTO_CYCLE_MINUTES||30))),createContent:automation.createContent??bool(process.env.AUTO_CREATE_CONTENT,true),autoApproveContent:s.autonomousMode===false?false:(automation.autoApproveContent??s.autoApproveContent??bool(process.env.AUTO_APPROVE_CONTENT,true)),autoPublish:s.autonomousMode===false?false:(automation.autoPublish??s.autoPublish??bool(process.env.AUTO_PUBLISH,true))}}}
function getConfig(){const r=runtimeSettings(),s=db.read().settings||{};return{timezone:r.timezone,niche:r.niche,queries:r.queries,xAccounts:r.xAccounts,maxOpportunities:r.maxOpportunities,search:{provider:r.searchProvider,configured:r.searchProvider==='tavily'?Boolean(r.tavilyApiKey):false},x:{enabled:Boolean(r.xBearerToken||r.xAccounts.length||process.env.X_USER_ACCESS_TOKEN||process.env.X_ACCESS_TOKEN),publishConfigured:Boolean(process.env.X_USER_ACCESS_TOKEN||process.env.X_ACCESS_TOKEN||s.xOAuth?.accessToken),oauthConfigured:Boolean(process.env.X_OAUTH_CLIENT_ID||s.xOAuthConfig?.clientId),oauthConnected:Boolean(s.xOAuth?.accessToken),oauthAccount:s.xOAuth?.account||null,accounts:r.xAccounts.length,discoveryConfigured:Boolean(r.xBearerToken&&r.xAccounts.length)},ai:{configured:Boolean(r.aiApiKey),model:r.aiModel,baseUrl:r.aiBaseUrl},automation:r.automation,profile:s.profile||{},strategy:s.strategy||{},preferences:s.preferences||{},notifications:s.notifications||{},ui:{hasTavilyKey:Boolean(r.tavilyApiKey),hasXBearerToken:Boolean(r.xBearerToken),hasAiApiKey:Boolean(r.aiApiKey),xAccounts:r.xAccounts}}}
function getRuntimeSecrets(){return runtimeSettings()}
module.exports={getConfig,getRuntimeSecrets};
