const crypto=require('crypto');
const db=require('../store/db');
const {runPipeline}=require('./pipeline');
const {runContentFactory}=require('./contentFactory');
const {publishDistribution,platformConfig}=require('../providers/publisher');
function now(){return new Date().toISOString()}
function connectedPlatforms(){return new Set(Object.entries(platformConfig()).filter(([,v])=>v?.configured&&!v?.manual).map(([n])=>n.toLowerCase()))}
function queueContentFormats(content){const formats=Array.isArray(content?.package?.formats)?content.package.formats:[],connected=connectedPlatforms(),d=db.read(),prefs=d.settings?.preferences||{},defaults=Array.isArray(prefs.defaultDestinations)&&prefs.defaultDestinations.length?prefs.defaultDestinations:null,existing=d.distribution.filter(x=>x.contentId===content.id&&!['cancelled','failed','blocked'].includes(x.status)),items=[],skipped=[];const candidates=defaults?formats.filter(f=>defaults.some(p=>String(p).toLowerCase()===String(f.platform||'').toLowerCase())):formats;for(const format of candidates){if(!format?.platform)continue;const platform=String(format.platform).trim();if(!connected.has(platform.toLowerCase())){skipped.push({platform,reason:'Publisher is not connected.'});continue}if(prefs.duplicateProtection!==false&&existing.some(x=>String(x.platform).toLowerCase()===platform.toLowerCase()))continue;items.push(db.addDistribution({id:crypto.randomUUID(),contentId:content.id,platform,type:format.type||'Draft',title:format.title||content.package?.hook||'Media package',body:format.body||content.package?.hook||'',mediaUrl:format.mediaUrl||content.package?.mediaUrl||null,mediaType:format.mediaType||content.package?.mediaType||null,link:format.link||content.package?.link||null,status:'queued',scheduledAt:null,createdAt:now(),publishedAt:null,externalId:null,externalUrl:null,lastError:null,autonomous:true,autoAttempts:0}))}return{items,skipped}}
function reconcileUnpublishableQueue(){const connected=connectedPlatforms(),d=db.read(),changed=[];for(const item of d.distribution){if(!item.autonomous||!['queued','ready'].includes(item.status))continue;if(connected.has(String(item.platform||'').toLowerCase()))continue;const u=db.updateDistribution(item.id,{status:'blocked',lastError:`${item.platform||'This'} publisher is not connected. Connect it to enable autonomous delivery.`,blockedAt:now()});if(u)changed.push(u)}return changed}
async function autonomousCycle(config={}){const settings=db.read().settings||{};if(settings.machineActive===false||config.automation?.enabled===false)return{skipped:true,reason:'Machine is paused.'};const started=Date.now();db.updateSettings({lastAutoCycleAt:now(),lastAutoStatus:'working'});try{const reconciled=reconcileUnpublishableQueue(),pipeline=await runPipeline(config),opportunities=Array.isArray(pipeline.opportunities)?pipeline.opportunities:[],createdContent=[],queued=[],blocked=[],maxContent=Math.min(opportunities.length,Math.max(1,Number(config.maxOpportunities||5)));if(config.automation?.createContent!==false){for(const opportunity of opportunities.slice(0,maxContent)){const recent=db.read().content.find(x=>x.opportunityId===opportunity.id);if(recent)continue;try{const content=await runContentFactory(opportunity);let finalContent=content;if(config.automation?.autoApproveContent===true)finalContent=db.updateContent(content.id,{status:'approved',reviewedAt:now(),reviewSource:'autonomous'});createdContent.push(finalContent);if(config.automation?.autoApproveContent===true){const routed=queueContentFormats(finalContent);queued.push(...routed.items);blocked.push(...routed.skipped)}}catch(error){createdContent.push({error:error.message,opportunityId:opportunity.id})}}}
 const published=[];if(config.automation?.autoPublish===true&&config.automation?.autoApproveContent===true){const connected=connectedPlatforms(),items=db.read().distribution.filter(x=>['queued','ready'].includes(x.status)&&x.autonomous&&connected.has(String(x.platform||'').toLowerCase())&&Number(x.autoAttempts||0)<3).slice(0,5);for(const item of items){db.updateDistribution(item.id,{autoAttempts:Number(item.autoAttempts||0)+1,lastAutoAttemptAt:now()});const result=await publishDistribution(item);if(result.ok){published.push(db.updateDistribution(item.id,{status:'published',publishedAt:now(),externalId:result.externalId||result.published?.[0]?.id||null,externalUrl:result.published?.[0]?.url||null,threadSize:result.threadSize||1,publishSource:'autonomous',lastError:null}))}else{db.updateDistribution(item.id,{status:result.manual?'ready':'failed',lastError:result.reason||'Autonomous publishing failed.',lastAttemptAt:now(),publishSource:'autonomous'})}}}
 const nextAt=new Date(Date.now()+Number(config.automation?.cycleMinutes||30)*60000).toISOString();db.updateSettings({lastAutoStatus:'completed',nextAutoCycleAt:nextAt});return{skipped:false,durationMs:Date.now()-started,pipeline,createdContent,queued,blocked,reconciled,published,nextAt};
 }catch(error){const nextAt=new Date(Date.now()+Number(config.automation?.cycleMinutes||30)*60000).toISOString();db.updateSettings({lastAutoStatus:'failed',nextAutoCycleAt:nextAt});throw error}}
module.exports={autonomousCycle,reconcileUnpublishableQueue};
