const crypto=require('crypto');
const {generateJSON}=require('../providers/ai');
const db=require('../store/db');
function fallback(opportunity){const title=opportunity?.signal?.title||opportunity?.strategy?.thesis||'Emerging opportunity',thesis=opportunity?.strategy?.thesis||opportunity?.research?.angle||title,hook=opportunity?.strategy?.hook||`Most people are looking at ${String(title).toLowerCase()} the wrong way.`,base=`${hook}\n\nHere is what changed, why it matters, and what to watch next.\n\n1/ Start with the strongest verified signal.\n2/ Explain the implication in plain English.\n3/ Give one practical takeaway.\n4/ Close with a useful question.`;return{thesis,hook,angle:'Explain the shift, show the evidence, then give the audience a practical implication.',formats:[
 {platform:'X',type:'Thread',title:hook,body:base},
 {platform:'YouTube',type:'Short',title:hook,body:`Hook: ${hook}\n\nBeat 1 — The signal.\nBeat 2 — Why it matters.\nBeat 3 — What most people miss.\nBeat 4 — What to watch next.`,mediaType:'VIDEO'},
 {platform:'Instagram',type:'Reel',title:hook,body:`Opening: ${hook}\n\nShow the evidence. Explain the shift. End with the practical takeaway.`,mediaType:'REELS'},
 {platform:'TikTok',type:'Video',title:hook,body:`Hook: ${hook}\nContext: ${thesis}\nPayoff: what the audience should do or watch next.`,mediaType:'VIDEO'},
 {platform:'LinkedIn',type:'Post',title:hook,body:`${thesis}\n\nThe useful question is what changes because of this signal. Here are the implications:\n\n• What changed\n• Why it matters\n• What to watch next`},
 {platform:'Facebook Pages',type:'Post',title:hook,body:`${thesis}\n\nHere is what changed, why it matters, and what to watch next.`},
 {platform:'Threads',type:'Post',title:hook,body:`${hook}\n\n${thesis}\n\nThe part worth watching is what happens next.`},
 {platform:'Pinterest',type:'Pin',title:hook,body:`${thesis}\n\nSave this signal and come back when the next update lands.`,mediaType:'IMAGE'},
 {platform:'Email',type:'Brief',title:`What ${title} means right now`,body:`The short version: ${thesis}\n\nThe evidence points to a meaningful shift. The useful question is not whether the trend exists, but what changes because of it.\n\nWe will keep watching the primary signals and update the thesis as new evidence arrives.`}
],visualDirection:['Clean editorial opening frame','One evidence-led chart or screenshot','Three short kinetic text beats','Minimal branded closing frame'],qa:['Every factual claim has a source','No invented quotes or statistics','Dates and figures are current','Hook matches the evidence','Platform format matches the destination','CTA is relevant and non-spammy']}}
async function createContent(opportunity){const prompt=`Build a publishable multi-platform content package from this Orvia opportunity. Never invent facts. Only use claims supported by the supplied evidence. Return JSON with thesis, hook, angle, formats [{platform,type,title,body,mediaType?,mediaUrl?,link?}], visualDirection array, qa array. Prefer platform-native writing and include these destinations when relevant: X, YouTube, Instagram, TikTok, LinkedIn, Facebook Pages, Threads, Pinterest, Email. Evidence beats fluency. Opportunity: ${JSON.stringify(opportunity)}`;try{return(await generateJSON('You are Orvia Content Director. You turn verified opportunities into original, platform-native media packages. Evidence beats fluency. Do not fabricate claims.',prompt))||fallback(opportunity)}catch{return fallback(opportunity)}}
async function runContentFactory(opportunity){if(!opportunity)throw new Error('Opportunity not found.');const started=Date.now(),generatedAt=new Date().toISOString(),stages=[{id:'brief',label:'Brief',status:'complete'},{id:'thesis',label:'Thesis',status:'complete'},{id:'draft',label:'Draft',status:'complete'},{id:'repurpose',label:'Repurpose',status:'complete'},{id:'qa',label:'Quality Control',status:'complete'}],packageData=await createContent(opportunity),item={id:crypto.randomUUID(),opportunityId:opportunity.id,createdAt:generatedAt,durationMs:Date.now()-started,status:'review',stages,events:[{agent:'CONTENT FACTORY',title:'Package generated',description:`Platform-native package assembled · ${Date.now()-started}ms`,status:'success',at:generatedAt},{agent:'QUALITY CONTROL',title:'Review gate',description:'Package held for editorial approval',status:'success',at:new Date().toISOString()}],package:packageData};db.addContent(item);return item}
module.exports={runContentFactory};
