const db=require('../store/db');
const {encrypt,decrypt}=require('../security');
const {saveConnection,readConnection,assertState,jsonFetch,redirectFor}=require('./oauth');
function config(){const s=db.read().settings?.connections?.metaConfig||{};return{clientId:String(s.clientId||process.env.META_CLIENT_ID||'').trim(),clientSecret:String(s.clientSecret?decrypt(s.clientSecret):process.env.META_CLIENT_SECRET||'').trim(),redirectUri:String(s.redirectUri||process.env.META_REDIRECT_URI||redirectFor('/api/publishing/meta/callback')).trim(),graphVersion:String(s.graphVersion||process.env.META_GRAPH_VERSION||'v24.0').trim(),scopes:String(s.scopes||process.env.META_SCOPES||'pages_show_list pages_read_engagement pages_manage_posts instagram_basic instagram_content_publish').trim().split(/\s+/).filter(Boolean)}}
const api=(version,path)=>`https://graph.facebook.com/${version}${path}`;
function safePages(pages){
  return (Array.isArray(pages)?pages:[]).map(p=>({
    id:p.id,
    name:p.name,
    instagramBusinessAccountId:p.instagramBusinessAccountId||null,
    accessTokenConfigured:Boolean(p.accessToken)
  }));
}
function status(){const cfg=config(),c=readConnection('meta')||{};return{platform:'Meta',configured:Boolean(cfg.clientId),redirectUri:cfg.redirectUri,scopes:cfg.scopes,connected:Boolean(c.accessToken),account:c.account||null,instagram:c.instagram||null,pages:safePages(c.pages),expiresAt:c.expiresAt||null,connectedAt:c.connectedAt||null,lastError:c.lastError||null,graphVersion:cfg.graphVersion};}
function authorizeUrl(){const cfg=config();if(!cfg.clientId)throw new Error('Meta is not configured yet. Add the Meta App ID in Settings → Advanced.');const state=require('crypto').randomBytes(32).toString('base64url');saveConnection('meta',{pending:{state,createdAt:Date.now()}});const p=new URLSearchParams({client_id:cfg.clientId,redirect_uri:cfg.redirectUri,response_type:'code',scope:cfg.scopes.join(','),state});return`https://www.facebook.com/${cfg.graphVersion}/dialog/oauth?${p}`;}
async function exchangeCode(code,state){const cfg=config();assertState('meta',state);const tokenData=await jsonFetch(api(cfg.graphVersion,'/oauth/access_token')+'?'+new URLSearchParams({client_id:cfg.clientId,client_secret:cfg.clientSecret,redirect_uri:cfg.redirectUri,code}).toString());const userToken=tokenData.access_token;const longData=await jsonFetch(api(cfg.graphVersion,'/oauth/access_token')+'?'+new URLSearchParams({grant_type:'fb_exchange_token',client_id:cfg.clientId,client_secret:cfg.clientSecret,fb_exchange_token:userToken}).toString()).catch(()=>tokenData);const token=longData.access_token||userToken;const assets=await fetchMetaAssets(token,cfg.graphVersion);const expiresIn=Number(longData.expires_in||tokenData.expires_in||0);saveConnection('meta',{accessToken:encrypt(token),expiresAt:expiresIn?Date.now()+Math.max(0,expiresIn-120)*1000:null,scope:cfg.scopes.join(' '),account:assets.user,instagram:assets.instagram,pages:assets.pages,connectedAt:new Date().toISOString(),lastError:null,pending:null});return status();}
async function getAccessToken(){const c=readConnection('meta');return c?.accessToken?decrypt(c.accessToken):'';}
async function fetchMetaAssets(token,version){const me=await jsonFetch(api(version,'/me?fields=id,name'),{headers:{Authorization:`Bearer ${token}`}});const pages=await jsonFetch(api(version,'/me/accounts?fields=id,name,access_token,instagram_business_account'),{headers:{Authorization:`Bearer ${token}`}}).catch(()=>({data:[]}));let instagram=null;const pageList=[];for(const p of pages.data||[]){let ig=p.instagram_business_account?.id?await jsonFetch(api(version,`/${p.instagram_business_account.id}?fields=id,username,name,profile_picture_url`),{headers:{Authorization:`Bearer ${token}`}}).catch(()=>null):null;pageList.push({id:p.id,name:p.name,accessToken:p.access_token?encrypt(p.access_token):null,instagramBusinessAccountId:p.instagram_business_account?.id||null});if(!instagram&&ig)instagram={...ig,pageId:p.id};}return{user:{id:me.id,name:me.name||''},pages:pageList,instagram};}
async function verifyConnection(){try{const token=await getAccessToken();if(!token)return{ok:false,configured:status().configured,connected:false,reason:'Meta is not connected.'};const cfg=config();const assets=await fetchMetaAssets(token,cfg.graphVersion);saveConnection('meta',{account:assets.user,instagram:assets.instagram,pages:assets.pages,lastVerifiedAt:new Date().toISOString(),lastError:null});return{ok:true,connected:true,account:assets.user,instagram:assets.instagram,pages:safePages(assets.pages)};}catch(e){saveConnection('meta',{lastError:e.message});return{ok:false,connected:true,reason:e.message};}}
async function disconnect(){db.updateSettings({connections:{...(db.read().settings?.connections||{}),meta:null,metaConfig:db.read().settings?.connections?.metaConfig||undefined}});return status();}
async function facebookPageToken(pageId){const c=readConnection('meta')||{};const page=Array.isArray(c.pages)?c.pages.find(x=>String(x.id)===String(pageId)):null;return page?.accessToken?decrypt(page.accessToken):'';}
async function publishFacebookPage({message,link,pageId}){const cfg=config();const c=status();const chosen=pageId?c.pages.find(x=>String(x.id)===String(pageId)):c.pages?.[0];if(!c.connected||!chosen)return{ok:false,manual:true,platform:'Facebook Pages',reason:'Connect a Meta account with at least one Facebook Page.'};const token=await facebookPageToken(chosen.id);const q=new URLSearchParams({message:String(message||'')});if(link)q.set('link',String(link));const data=await jsonFetch(api(cfg.graphVersion,`/${chosen.id}/feed?${q}`),{method:'POST',headers:{Authorization:`Bearer ${token}`}});return{ok:true,platform:'Facebook Pages',externalId:data.id,published:[{id:data.id,url:`https://www.facebook.com/${data.id}`}]};}
async function publishInstagram({caption,mediaUrl,mediaType='IMAGE'}){const cfg=config(),c=status();if(!c.connected||!c.instagram?.id)return{ok:false,manual:true,platform:'Instagram',reason:'Connect a Meta account with an Instagram Professional account.'};if(!mediaUrl)return{ok:false,manual:true,platform:'Instagram',reason:'Instagram publishing requires a publicly accessible image or video URL.'};const token=await getAccessToken();const id=c.instagram.id;const type=String(mediaType).toUpperCase();const params={caption:String(caption||''),access_token:token};if(type==='VIDEO'||type==='REELS'){params.media_type='REELS';params.video_url=mediaUrl;}else{params.image_url=mediaUrl;}const create=await jsonFetch(api(cfg.graphVersion,`/${id}/media?${new URLSearchParams(params)}`),{method:'POST'});let publishedId=create.id;if(type==='VIDEO'||type==='REELS'){for(let i=0;i<12;i++){await new Promise(r=>setTimeout(r,1500));const check=await jsonFetch(api(cfg.graphVersion,`/${create.id}?fields=status_code,status&access_token=${token}`)).catch(()=>null);const state=String(check?.status_code||check?.status||'').toUpperCase();if(['FINISHED','PUBLISHED','READY'].some(x=>state.includes(x)))break;if(state.includes('ERROR')||state.includes('FAILED'))throw new Error(`Instagram media processing failed: ${check?.status||check?.status_code||'unknown status'}`);}}const publish=await jsonFetch(api(cfg.graphVersion,`/${id}/media_publish?${new URLSearchParams({creation_id:create.id,access_token:token})}`),{method:'POST'});publishedId=publish.id||publishedId;return{ok:true,platform:'Instagram',externalId:publishedId,published:[{id:publishedId,url:`https://www.instagram.com/`}]};}
module.exports={config,status,authorizeUrl,exchangeCode,getAccessToken,verifyConnection,disconnect,facebookPageToken,publishFacebookPage,publishInstagram};
