const db=require('../store/db');
const {encrypt,decrypt}=require('../security');
const {saveConnection,readConnection,assertState,formPost,jsonFetch,tokenExpiresSoon,redirectFor}=require('./oauth');
function config(){const s=db.read().settings?.connections?.threadsConfig||{};return{clientId:String(s.clientId||process.env.THREADS_CLIENT_ID||'').trim(),clientSecret:String(s.clientSecret?decrypt(s.clientSecret):process.env.THREADS_CLIENT_SECRET||'').trim(),redirectUri:String(s.redirectUri||process.env.THREADS_REDIRECT_URI||redirectFor('/api/publishing/threads/callback')).trim(),scopes:String(s.scopes||process.env.THREADS_SCOPES||'threads_basic,threads_content_publish').trim().split(/[ ,]+/).filter(Boolean)}}
const API='https://graph.threads.net';
function status(){const c=readConnection('threads')||{},cfg=config();return{platform:'Threads',configured:Boolean(cfg.clientId),redirectUri:cfg.redirectUri,scopes:cfg.scopes,connected:Boolean(c.accessToken),account:c.account||null,expiresAt:c.expiresAt||null,connectedAt:c.connectedAt||null,lastError:c.lastError||null};}
function authorizeUrl(){const cfg=config();if(!cfg.clientId)throw new Error('Threads is not configured yet. Add the Threads App ID in Settings → Advanced.');const state= require('crypto').randomBytes(32).toString('base64url');saveConnection('threads',{pending:{state,createdAt:Date.now()}});const p=new URLSearchParams({client_id:cfg.clientId,redirect_uri:cfg.redirectUri,response_type:'code',scope:cfg.scopes.join(','),state});return`${API}/oauth/authorize?${p}`;}
async function exchangeCode(code,state){const cfg=config();const pending=readConnection('threads')?.pending;if(!pending||pending.state!==state)throw new Error('Invalid or expired Threads connection session.');const data=await jsonFetch(`${API}/oauth/access_token?${new URLSearchParams({client_id:cfg.clientId,client_secret:cfg.clientSecret,code,grant_type:'authorization_code',redirect_uri:cfg.redirectUri}).toString()}`,{method:'POST'});const long=await jsonFetch(`${API}/access_token?${new URLSearchParams({grant_type:'th_exchange_token',client_secret:cfg.clientSecret}).toString()}`,{headers:{Authorization:`Bearer ${data.access_token}`}}).catch(()=>data);const token=long.access_token||data.access_token;const account=await fetchMe(token);saveConnection('threads',{accessToken:encrypt(token),expiresAt:long.expires_in?Date.now()+Math.max(0,Number(long.expires_in)-120)*1000:null,scope:cfg.scopes.join(','),userId:data.user_id,account,connectedAt:new Date().toISOString(),lastError:null,pending:null});return status();}
async function getAccessToken(){const c=readConnection('threads');return c?.accessToken?decrypt(c.accessToken):'';}
async function fetchMe(token){const r=await jsonFetch(`${API}/me?fields=id,username,name,threads_profile_picture_url&access_token=${encodeURIComponent(token)}`);return r?.data||r||{};}
async function verifyConnection(){try{const token=await getAccessToken();if(!token)return{ok:false,configured:status().configured,connected:false,reason:'Threads is not connected.'};const account=await fetchMe(token);saveConnection('threads',{account,lastVerifiedAt:new Date().toISOString(),lastError:null});return{ok:true,connected:true,account};}catch(e){saveConnection('threads',{lastError:e.message});return{ok:false,connected:true,reason:e.message};}}
async function disconnect(){db.updateSettings({connections:{...(db.read().settings?.connections||{}),threads:null,threadsConfig:db.read().settings?.connections?.threadsConfig||undefined}});return status();}
async function publishText(body){const token=await getAccessToken();if(!token)return{ok:false,manual:true,platform:'Threads',reason:'Threads is not connected.'};const create=await jsonFetch(`${API}/me/threads?${new URLSearchParams({text:String(body||''),media_type:'TEXT',auto_publish_text:'true',access_token:token})}`,{method:'POST'});return{ok:true,externalId:create.id,published:[{id:create.id,url:`https://www.threads.net/@${encodeURIComponent(readConnection('threads')?.account?.username||'')}/post/${create.id}`}],threadSize:1};}
module.exports={config,status,authorizeUrl,exchangeCode,getAccessToken,verifyConnection,disconnect,publishText};
